// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autogen.proto

package dev.zaryxstudios.zaryxnear.proto;

public final class Autogen {
  private Autogen() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JarUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JarUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JarDocsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JarDocsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rautogen.proto\"\211\001\n\020JarUploadRequest\022\023\n\013" +
      "jar_content\030\001 \001(\014\022\021\n\tfile_name\030\002 \001(\t\022!\n\t" +
      "scan_mode\030\003 \001(\0162\016.ScanModeProto\022\031\n\014packa" +
      "ge_path\030\004 \001(\tH\000\210\001\001B\017\n\r_package_path\"j\n\017J" +
      "arDocsResponse\022\017\n\007success\030\001 \001(\010\022\030\n\020markd" +
      "own_content\030\002 \001(\t\022\025\n\rerror_message\030\003 \001(\t" +
      "\022\025\n\rclasses_found\030\004 \001(\003*3\n\rScanModeProto" +
      "\022\014\n\010FULL_JAR\020\000\022\024\n\020PACKAGE_SPECIFIC\020\0012F\n\017" +
      "JarDocGenerator\0223\n\014GenerateDocs\022\021.JarUpl" +
      "oadRequest\032\020.JarDocsResponseB-\n dev.zary" +
      "xstudios.zaryxnear.protoB\007AutogenP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JarUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JarUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JarUploadRequest_descriptor,
        new java.lang.String[] { "JarContent", "FileName", "ScanMode", "PackagePath", "PackagePath", });
    internal_static_JarDocsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JarDocsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JarDocsResponse_descriptor,
        new java.lang.String[] { "Success", "MarkdownContent", "ErrorMessage", "ClassesFound", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
