// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autogen.proto

package dev.zaryxstudios.zaryxnear.proto;

public interface JarDocsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JarDocsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string markdown_content = 2;</code>
   * @return The markdownContent.
   */
  java.lang.String getMarkdownContent();
  /**
   * <code>string markdown_content = 2;</code>
   * @return The bytes for markdownContent.
   */
  com.google.protobuf.ByteString
      getMarkdownContentBytes();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>int64 classes_found = 4;</code>
   * @return The classesFound.
   */
  long getClassesFound();
}
