// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autogen.proto

package dev.zaryxstudios.zaryxnear.proto;

public interface JarUploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JarUploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes jar_content = 1;</code>
   * @return The jarContent.
   */
  com.google.protobuf.ByteString getJarContent();

  /**
   * <code>string file_name = 2;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 2;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>.ScanModeProto scan_mode = 3;</code>
   * @return The enum numeric value on the wire for scanMode.
   */
  int getScanModeValue();
  /**
   * <code>.ScanModeProto scan_mode = 3;</code>
   * @return The scanMode.
   */
  dev.zaryxstudios.zaryxnear.proto.ScanModeProto getScanMode();

  /**
   * <code>optional string package_path = 4;</code>
   * @return Whether the packagePath field is set.
   */
  boolean hasPackagePath();
  /**
   * <code>optional string package_path = 4;</code>
   * @return The packagePath.
   */
  java.lang.String getPackagePath();
  /**
   * <code>optional string package_path = 4;</code>
   * @return The bytes for packagePath.
   */
  com.google.protobuf.ByteString
      getPackagePathBytes();
}
