// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autogen.proto

package dev.zaryxstudios.zaryxnear.proto;

/**
 * Protobuf type {@code JarUploadRequest}
 */
public final class JarUploadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JarUploadRequest)
    JarUploadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JarUploadRequest.newBuilder() to construct.
  private JarUploadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JarUploadRequest() {
    jarContent_ = com.google.protobuf.ByteString.EMPTY;
    fileName_ = "";
    scanMode_ = 0;
    packagePath_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JarUploadRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.zaryxstudios.zaryxnear.proto.Autogen.internal_static_JarUploadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.zaryxstudios.zaryxnear.proto.Autogen.internal_static_JarUploadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.class, dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.Builder.class);
  }

  private int bitField0_;
  public static final int JAR_CONTENT_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString jarContent_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes jar_content = 1;</code>
   * @return The jarContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getJarContent() {
    return jarContent_;
  }

  public static final int FILE_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileName_ = "";
  /**
   * <code>string file_name = 2;</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string file_name = 2;</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCAN_MODE_FIELD_NUMBER = 3;
  private int scanMode_ = 0;
  /**
   * <code>.ScanModeProto scan_mode = 3;</code>
   * @return The enum numeric value on the wire for scanMode.
   */
  @java.lang.Override public int getScanModeValue() {
    return scanMode_;
  }
  /**
   * <code>.ScanModeProto scan_mode = 3;</code>
   * @return The scanMode.
   */
  @java.lang.Override public dev.zaryxstudios.zaryxnear.proto.ScanModeProto getScanMode() {
    dev.zaryxstudios.zaryxnear.proto.ScanModeProto result = dev.zaryxstudios.zaryxnear.proto.ScanModeProto.forNumber(scanMode_);
    return result == null ? dev.zaryxstudios.zaryxnear.proto.ScanModeProto.UNRECOGNIZED : result;
  }

  public static final int PACKAGE_PATH_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packagePath_ = "";
  /**
   * <code>optional string package_path = 4;</code>
   * @return Whether the packagePath field is set.
   */
  @java.lang.Override
  public boolean hasPackagePath() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string package_path = 4;</code>
   * @return The packagePath.
   */
  @java.lang.Override
  public java.lang.String getPackagePath() {
    java.lang.Object ref = packagePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packagePath_ = s;
      return s;
    }
  }
  /**
   * <code>optional string package_path = 4;</code>
   * @return The bytes for packagePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackagePathBytes() {
    java.lang.Object ref = packagePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packagePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!jarContent_.isEmpty()) {
      output.writeBytes(1, jarContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
    }
    if (scanMode_ != dev.zaryxstudios.zaryxnear.proto.ScanModeProto.FULL_JAR.getNumber()) {
      output.writeEnum(3, scanMode_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, packagePath_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!jarContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, jarContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
    }
    if (scanMode_ != dev.zaryxstudios.zaryxnear.proto.ScanModeProto.FULL_JAR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, scanMode_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, packagePath_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.zaryxstudios.zaryxnear.proto.JarUploadRequest)) {
      return super.equals(obj);
    }
    dev.zaryxstudios.zaryxnear.proto.JarUploadRequest other = (dev.zaryxstudios.zaryxnear.proto.JarUploadRequest) obj;

    if (!getJarContent()
        .equals(other.getJarContent())) return false;
    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (scanMode_ != other.scanMode_) return false;
    if (hasPackagePath() != other.hasPackagePath()) return false;
    if (hasPackagePath()) {
      if (!getPackagePath()
          .equals(other.getPackagePath())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JAR_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getJarContent().hashCode();
    hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + SCAN_MODE_FIELD_NUMBER;
    hash = (53 * hash) + scanMode_;
    if (hasPackagePath()) {
      hash = (37 * hash) + PACKAGE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPackagePath().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.zaryxstudios.zaryxnear.proto.JarUploadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JarUploadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JarUploadRequest)
      dev.zaryxstudios.zaryxnear.proto.JarUploadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zaryxstudios.zaryxnear.proto.Autogen.internal_static_JarUploadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zaryxstudios.zaryxnear.proto.Autogen.internal_static_JarUploadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.class, dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.Builder.class);
    }

    // Construct using dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      jarContent_ = com.google.protobuf.ByteString.EMPTY;
      fileName_ = "";
      scanMode_ = 0;
      packagePath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.zaryxstudios.zaryxnear.proto.Autogen.internal_static_JarUploadRequest_descriptor;
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.proto.JarUploadRequest getDefaultInstanceForType() {
      return dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.proto.JarUploadRequest build() {
      dev.zaryxstudios.zaryxnear.proto.JarUploadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.proto.JarUploadRequest buildPartial() {
      dev.zaryxstudios.zaryxnear.proto.JarUploadRequest result = new dev.zaryxstudios.zaryxnear.proto.JarUploadRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.zaryxstudios.zaryxnear.proto.JarUploadRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.jarContent_ = jarContent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileName_ = fileName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.scanMode_ = scanMode_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.packagePath_ = packagePath_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.zaryxstudios.zaryxnear.proto.JarUploadRequest) {
        return mergeFrom((dev.zaryxstudios.zaryxnear.proto.JarUploadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.zaryxstudios.zaryxnear.proto.JarUploadRequest other) {
      if (other == dev.zaryxstudios.zaryxnear.proto.JarUploadRequest.getDefaultInstance()) return this;
      if (other.getJarContent() != com.google.protobuf.ByteString.EMPTY) {
        setJarContent(other.getJarContent());
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.scanMode_ != 0) {
        setScanModeValue(other.getScanModeValue());
      }
      if (other.hasPackagePath()) {
        packagePath_ = other.packagePath_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              jarContent_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              fileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              scanMode_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              packagePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString jarContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes jar_content = 1;</code>
     * @return The jarContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getJarContent() {
      return jarContent_;
    }
    /**
     * <code>bytes jar_content = 1;</code>
     * @param value The jarContent to set.
     * @return This builder for chaining.
     */
    public Builder setJarContent(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      jarContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bytes jar_content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJarContent() {
      bitField0_ = (bitField0_ & ~0x00000001);
      jarContent_ = getDefaultInstance().getJarContent();
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string file_name = 2;</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_name = 2;</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_name = 2;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 2;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int scanMode_ = 0;
    /**
     * <code>.ScanModeProto scan_mode = 3;</code>
     * @return The enum numeric value on the wire for scanMode.
     */
    @java.lang.Override public int getScanModeValue() {
      return scanMode_;
    }
    /**
     * <code>.ScanModeProto scan_mode = 3;</code>
     * @param value The enum numeric value on the wire for scanMode to set.
     * @return This builder for chaining.
     */
    public Builder setScanModeValue(int value) {
      scanMode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.ScanModeProto scan_mode = 3;</code>
     * @return The scanMode.
     */
    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.proto.ScanModeProto getScanMode() {
      dev.zaryxstudios.zaryxnear.proto.ScanModeProto result = dev.zaryxstudios.zaryxnear.proto.ScanModeProto.forNumber(scanMode_);
      return result == null ? dev.zaryxstudios.zaryxnear.proto.ScanModeProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.ScanModeProto scan_mode = 3;</code>
     * @param value The scanMode to set.
     * @return This builder for chaining.
     */
    public Builder setScanMode(dev.zaryxstudios.zaryxnear.proto.ScanModeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      scanMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ScanModeProto scan_mode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearScanMode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      scanMode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object packagePath_ = "";
    /**
     * <code>optional string package_path = 4;</code>
     * @return Whether the packagePath field is set.
     */
    public boolean hasPackagePath() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string package_path = 4;</code>
     * @return The packagePath.
     */
    public java.lang.String getPackagePath() {
      java.lang.Object ref = packagePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packagePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string package_path = 4;</code>
     * @return The bytes for packagePath.
     */
    public com.google.protobuf.ByteString
        getPackagePathBytes() {
      java.lang.Object ref = packagePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packagePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string package_path = 4;</code>
     * @param value The packagePath to set.
     * @return This builder for chaining.
     */
    public Builder setPackagePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packagePath_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_path = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackagePath() {
      packagePath_ = getDefaultInstance().getPackagePath();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string package_path = 4;</code>
     * @param value The bytes for packagePath to set.
     * @return This builder for chaining.
     */
    public Builder setPackagePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      packagePath_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:JarUploadRequest)
  }

  // @@protoc_insertion_point(class_scope:JarUploadRequest)
  private static final dev.zaryxstudios.zaryxnear.proto.JarUploadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.zaryxstudios.zaryxnear.proto.JarUploadRequest();
  }

  public static dev.zaryxstudios.zaryxnear.proto.JarUploadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JarUploadRequest>
      PARSER = new com.google.protobuf.AbstractParser<JarUploadRequest>() {
    @java.lang.Override
    public JarUploadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JarUploadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JarUploadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.zaryxstudios.zaryxnear.proto.JarUploadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

