// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

public interface CategoryTreeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zaryxnear.docs.community.CategoryTreeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  int getCategoryTreeCount();
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  boolean containsCategoryTree(
      java.lang.String key);
  /**
   * Use {@link #getCategoryTreeMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
  getCategoryTree();
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
  getCategoryTreeMap();
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  /* nullable */
dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getCategoryTreeOrDefault(
      java.lang.String key,
      /* nullable */
dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList defaultValue);
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getCategoryTreeOrThrow(
      java.lang.String key);
}
