// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

/**
 * Protobuf type {@code zaryxnear.docs.community.CategoryTreeResponse}
 */
public final class CategoryTreeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:zaryxnear.docs.community.CategoryTreeResponse)
    CategoryTreeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CategoryTreeResponse.newBuilder() to construct.
  private CategoryTreeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CategoryTreeResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CategoryTreeResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetCategoryTree();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_CategoryTreeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.class, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.Builder.class);
  }

  public static final int CATEGORY_TREE_FIELD_NUMBER = 1;
  private static final class CategoryTreeDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>newDefaultInstance(
                dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_CategoryTreeResponse_CategoryTreeEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> categoryTree_;
  private com.google.protobuf.MapField<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
  internalGetCategoryTree() {
    if (categoryTree_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CategoryTreeDefaultEntryHolder.defaultEntry);
    }
    return categoryTree_;
  }
  public int getCategoryTreeCount() {
    return internalGetCategoryTree().getMap().size();
  }
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  @java.lang.Override
  public boolean containsCategoryTree(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetCategoryTree().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCategoryTreeMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> getCategoryTree() {
    return getCategoryTreeMap();
  }
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> getCategoryTreeMap() {
    return internalGetCategoryTree().getMap();
  }
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getCategoryTreeOrDefault(
      java.lang.String key,
      /* nullable */
dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> map =
        internalGetCategoryTree().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
   */
  @java.lang.Override
  public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getCategoryTreeOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> map =
        internalGetCategoryTree().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetCategoryTree(),
        CategoryTreeDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> entry
         : internalGetCategoryTree().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
      categoryTree__ = CategoryTreeDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, categoryTree__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse)) {
      return super.equals(obj);
    }
    dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse other = (dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse) obj;

    if (!internalGetCategoryTree().equals(
        other.internalGetCategoryTree())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetCategoryTree().getMap().isEmpty()) {
      hash = (37 * hash) + CATEGORY_TREE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCategoryTree().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code zaryxnear.docs.community.CategoryTreeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:zaryxnear.docs.community.CategoryTreeResponse)
      dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetCategoryTree();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableCategoryTree();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_CategoryTreeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.class, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.Builder.class);
    }

    // Construct using dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableCategoryTree().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor;
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse getDefaultInstanceForType() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse build() {
      dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse buildPartial() {
      dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse result = new dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.categoryTree_ = internalGetCategoryTree();
        result.categoryTree_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse) {
        return mergeFrom((dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse other) {
      if (other == dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse.getDefaultInstance()) return this;
      internalGetMutableCategoryTree().mergeFrom(
          other.internalGetCategoryTree());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
              categoryTree__ = input.readMessage(
                  CategoryTreeDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableCategoryTree().getMutableMap().put(
                  categoryTree__.getKey(), categoryTree__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> categoryTree_;
    private com.google.protobuf.MapField<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
        internalGetCategoryTree() {
      if (categoryTree_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CategoryTreeDefaultEntryHolder.defaultEntry);
      }
      return categoryTree_;
    }
    private com.google.protobuf.MapField<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
        internalGetMutableCategoryTree() {
      if (categoryTree_ == null) {
        categoryTree_ = com.google.protobuf.MapField.newMapField(
            CategoryTreeDefaultEntryHolder.defaultEntry);
      }
      if (!categoryTree_.isMutable()) {
        categoryTree_ = categoryTree_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return categoryTree_;
    }
    public int getCategoryTreeCount() {
      return internalGetCategoryTree().getMap().size();
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    @java.lang.Override
    public boolean containsCategoryTree(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCategoryTree().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCategoryTreeMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> getCategoryTree() {
      return getCategoryTreeMap();
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> getCategoryTreeMap() {
      return internalGetCategoryTree().getMap();
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getCategoryTreeOrDefault(
        java.lang.String key,
        /* nullable */
dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> map =
          internalGetCategoryTree().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getCategoryTreeOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> map =
          internalGetCategoryTree().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearCategoryTree() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableCategoryTree().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    public Builder removeCategoryTree(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableCategoryTree().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList>
        getMutableCategoryTree() {
      bitField0_ |= 0x00000001;
      return internalGetMutableCategoryTree().getMutableMap();
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    public Builder putCategoryTree(
        java.lang.String key,
        dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableCategoryTree().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .zaryxnear.docs.community.DocList&gt; category_tree = 1;</code>
     */
    public Builder putAllCategoryTree(
        java.util.Map<java.lang.String, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList> values) {
      internalGetMutableCategoryTree().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:zaryxnear.docs.community.CategoryTreeResponse)
  }

  // @@protoc_insertion_point(class_scope:zaryxnear.docs.community.CategoryTreeResponse)
  private static final dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse();
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CategoryTreeResponse>
      PARSER = new com.google.protobuf.AbstractParser<CategoryTreeResponse>() {
    @java.lang.Override
    public CategoryTreeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CategoryTreeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CategoryTreeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.CategoryTreeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

