// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

public interface DocListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zaryxnear.docs.community.DocList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string doc_id = 1;</code>
   * @return A list containing the docId.
   */
  java.util.List<java.lang.String>
      getDocIdList();
  /**
   * <code>repeated string doc_id = 1;</code>
   * @return The count of docId.
   */
  int getDocIdCount();
  /**
   * <code>repeated string doc_id = 1;</code>
   * @param index The index of the element to return.
   * @return The docId at the given index.
   */
  java.lang.String getDocId(int index);
  /**
   * <code>repeated string doc_id = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the docId at the given index.
   */
  com.google.protobuf.ByteString
      getDocIdBytes(int index);
}
