// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

/**
 * Protobuf type {@code zaryxnear.docs.community.DocList}
 */
public final class DocList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:zaryxnear.docs.community.DocList)
    DocListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DocList.newBuilder() to construct.
  private DocList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DocList() {
    docId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DocList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_DocList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_DocList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.class, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.Builder.class);
  }

  public static final int DOC_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList docId_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string doc_id = 1;</code>
   * @return A list containing the docId.
   */
  public com.google.protobuf.ProtocolStringList
      getDocIdList() {
    return docId_;
  }
  /**
   * <code>repeated string doc_id = 1;</code>
   * @return The count of docId.
   */
  public int getDocIdCount() {
    return docId_.size();
  }
  /**
   * <code>repeated string doc_id = 1;</code>
   * @param index The index of the element to return.
   * @return The docId at the given index.
   */
  public java.lang.String getDocId(int index) {
    return docId_.get(index);
  }
  /**
   * <code>repeated string doc_id = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the docId at the given index.
   */
  public com.google.protobuf.ByteString
      getDocIdBytes(int index) {
    return docId_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < docId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, docId_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < docId_.size(); i++) {
        dataSize += computeStringSizeNoTag(docId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDocIdList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList)) {
      return super.equals(obj);
    }
    dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList other = (dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList) obj;

    if (!getDocIdList()
        .equals(other.getDocIdList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDocIdCount() > 0) {
      hash = (37 * hash) + DOC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDocIdList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code zaryxnear.docs.community.DocList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:zaryxnear.docs.community.DocList)
      dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_DocList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_DocList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.class, dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.Builder.class);
    }

    // Construct using dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      docId_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocProto.internal_static_zaryxnear_docs_community_DocList_descriptor;
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getDefaultInstanceForType() {
      return dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.getDefaultInstance();
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList build() {
      dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList buildPartial() {
      dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList result = new dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        docId_.makeImmutable();
        result.docId_ = docId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList) {
        return mergeFrom((dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList other) {
      if (other == dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList.getDefaultInstance()) return this;
      if (!other.docId_.isEmpty()) {
        if (docId_.isEmpty()) {
          docId_ = other.docId_;
          bitField0_ |= 0x00000001;
        } else {
          ensureDocIdIsMutable();
          docId_.addAll(other.docId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDocIdIsMutable();
              docId_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList docId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDocIdIsMutable() {
      if (!docId_.isModifiable()) {
        docId_ = new com.google.protobuf.LazyStringArrayList(docId_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @return A list containing the docId.
     */
    public com.google.protobuf.ProtocolStringList
        getDocIdList() {
      docId_.makeImmutable();
      return docId_;
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @return The count of docId.
     */
    public int getDocIdCount() {
      return docId_.size();
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @param index The index of the element to return.
     * @return The docId at the given index.
     */
    public java.lang.String getDocId(int index) {
      return docId_.get(index);
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the docId at the given index.
     */
    public com.google.protobuf.ByteString
        getDocIdBytes(int index) {
      return docId_.getByteString(index);
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @param index The index to set the value at.
     * @param value The docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocId(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDocIdIsMutable();
      docId_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @param value The docId to add.
     * @return This builder for chaining.
     */
    public Builder addDocId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDocIdIsMutable();
      docId_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @param values The docId to add.
     * @return This builder for chaining.
     */
    public Builder addAllDocId(
        java.lang.Iterable<java.lang.String> values) {
      ensureDocIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, docId_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocId() {
      docId_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string doc_id = 1;</code>
     * @param value The bytes of the docId to add.
     * @return This builder for chaining.
     */
    public Builder addDocIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDocIdIsMutable();
      docId_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:zaryxnear.docs.community.DocList)
  }

  // @@protoc_insertion_point(class_scope:zaryxnear.docs.community.DocList)
  private static final dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList();
  }

  public static dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DocList>
      PARSER = new com.google.protobuf.AbstractParser<DocList>() {
    @java.lang.Override
    public DocList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DocList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DocList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.zaryxstudios.zaryxnear.ai.context.docs.community.config.DocList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

