// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

public final class DocProto {
  private DocProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zaryxnear_docs_community_DocResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zaryxnear_docs_community_DocResponseProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zaryxnear_docs_community_DocRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zaryxnear_docs_community_DocRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zaryxnear_docs_community_CategoryTreeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zaryxnear_docs_community_CategoryTreeResponse_CategoryTreeEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zaryxnear_docs_community_CategoryTreeResponse_CategoryTreeEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zaryxnear_docs_community_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zaryxnear_docs_community_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zaryxnear_docs_community_DocList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zaryxnear_docs_community_DocList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023community_doc.proto\022\030zaryxnear.docs.co" +
      "mmunity\"3\n\020DocResponseProto\022\017\n\007content\030\001" +
      " \001(\t\022\016\n\006tokens\030\002 \001(\003\"G\n\017DocRequestProto\022" +
      "\020\n\010category\030\001 \001(\t\022\023\n\013subcategory\030\002 \001(\t\022\r" +
      "\n\005docId\030\003 \001(\t\"\307\001\n\024CategoryTreeResponse\022W" +
      "\n\rcategory_tree\030\001 \003(\0132@.zaryxnear.docs.c" +
      "ommunity.CategoryTreeResponse.CategoryTr" +
      "eeEntry\032V\n\021CategoryTreeEntry\022\013\n\003key\030\001 \001(" +
      "\t\0220\n\005value\030\002 \001(\0132!.zaryxnear.docs.commun" +
      "ity.DocList:\0028\001\"\016\n\014EmptyRequest\"\031\n\007DocLi" +
      "st\022\016\n\006doc_id\030\001 \003(\t2\340\001\n\003Doc\022l\n\021GetDocInfo" +
      "rmation\022).zaryxnear.docs.community.DocRe" +
      "questProto\032*.zaryxnear.docs.community.Do" +
      "cResponseProto\"\000\022k\n\017GetCategoryTree\022&.za" +
      "ryxnear.docs.community.EmptyRequest\032..za" +
      "ryxnear.docs.community.CategoryTreeRespo" +
      "nse\"\000BI\n;dev.zaryxstudios.zaryxnear.ai.c" +
      "ontext.docs.community.configB\010DocProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zaryxnear_docs_community_DocResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zaryxnear_docs_community_DocResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zaryxnear_docs_community_DocResponseProto_descriptor,
        new java.lang.String[] { "Content", "Tokens", });
    internal_static_zaryxnear_docs_community_DocRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zaryxnear_docs_community_DocRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zaryxnear_docs_community_DocRequestProto_descriptor,
        new java.lang.String[] { "Category", "Subcategory", "DocId", });
    internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zaryxnear_docs_community_CategoryTreeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor,
        new java.lang.String[] { "CategoryTree", });
    internal_static_zaryxnear_docs_community_CategoryTreeResponse_CategoryTreeEntry_descriptor =
      internal_static_zaryxnear_docs_community_CategoryTreeResponse_descriptor.getNestedTypes().get(0);
    internal_static_zaryxnear_docs_community_CategoryTreeResponse_CategoryTreeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zaryxnear_docs_community_CategoryTreeResponse_CategoryTreeEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_zaryxnear_docs_community_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_zaryxnear_docs_community_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zaryxnear_docs_community_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_zaryxnear_docs_community_DocList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_zaryxnear_docs_community_DocList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zaryxnear_docs_community_DocList_descriptor,
        new java.lang.String[] { "DocId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
