// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

public interface DocResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zaryxnear.docs.community.DocResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int64 tokens = 2;</code>
   * @return The tokens.
   */
  long getTokens();
}
