// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

public interface DocRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zaryxnear.docs.community.DocRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string category = 1;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 1;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>string subcategory = 2;</code>
   * @return The subcategory.
   */
  java.lang.String getSubcategory();
  /**
   * <code>string subcategory = 2;</code>
   * @return The bytes for subcategory.
   */
  com.google.protobuf.ByteString
      getSubcategoryBytes();

  /**
   * <code>string docId = 3;</code>
   * @return The docId.
   */
  java.lang.String getDocId();
  /**
   * <code>string docId = 3;</code>
   * @return The bytes for docId.
   */
  com.google.protobuf.ByteString
      getDocIdBytes();
}
