// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community_doc.proto

package dev.zaryxstudios.zaryxnear.ai.context.docs.community.config;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zaryxnear.docs.community.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
